### ISSUE TITLE
Telegram integration

### ISSUE THREAD

**Issue by talentlessguy** [go-joe/joe#19]
Is there any example with [Telegram](https://telegram.org)? Would be cool to see a small example :)

**Comment by fgrosse** [comment]
You would have to write a new [`Adapter`][1] implementation for this. So far there is only a slack adapter https://github.com/go-joe/slack-adapter and @dwmunster recently implemented a Rocket.Chat Adapter via #20 

You are more then welcome if you want to give it a try and I can give you some directions in case something is unclear from the docs or the two other implementations :)

[1]: https://github.com/go-joe/joe/blob/0c01d0e943bd7d660801fa79e8a05fd2d3ad0523/adapter.go#L21-L25

**Comment by talentlessguy** [comment]
Okay, I'll take a look at `Adapter`

**Comment by fgrosse** [comment]
Closed via #22

**Comment by talentlessguy** [comment]
nice!
