### ISSUE TITLE
Slack DM

### ISSUE THREAD

**Issue by vic3lord** [go-joe/joe#48]
Is there a way to message.Send DMs to users?
I'm sorry about the question but I couldn't find any reference to this in slack-adapter nor here.

**Comment by fgrosse** [comment]
Hey @vic3lord 

For slack, direct messages are also just a specific kind of "channel". If you know the slack user ID of the person you want to send your DM but not the channel name, then you can get it via: the [`Client.OpenIMChannel(…)`][1] function.

Now when you have the channel, I think you should be able to just put it into the [`Bot.Say(…)`][2] function. If you need more sophisticated formatting or wonder about a good pattern to access the `OpenIMChannel` function, have a look at https://joe-bot.net/recipes/slack/ :)

Hope this helps

[1]: https://pkg.go.dev/github.com/slack-go/slack#Client.OpenIMChannel
[2]: https://pkg.go.dev/github.com/go-joe/joe#Bot.Say

**Comment by vic3lord** [comment]
Thanks, exactly what I needed!
